# Generated by Django 3.2.19 on 2023-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enspd',
            name='image',
            field=models.ImageField(null=True, upload_to='image_des_epreuves'),
        ),
    ]
